<a href="https://colab.research.google.com/github/shubhamsinha21/deep_learning_pytorch/blob/main/Intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
myList = [[1,2,3,4], [5,6,7,8]]
myList

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.88102284, 0.42055779, 0.23076896, 0.33390557],
       [0.88777254, 0.71640769, 0.63459152, 0.92428552],
       [0.51230321, 0.26926366, 0.98201518, 0.88187133]])

**TENSOR**
(Creating a pytorch 2d tensor)

In [ ]:
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7575, -0.4784, -1.0925,  0.0685],
        [ 1.0653,  0.4483,  2.6467,  1.4122],
        [ 0.0622,  0.2454,  1.6882, -0.4113]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8810, 0.4206, 0.2308, 0.3339],
        [0.8878, 0.7164, 0.6346, 0.9243],
        [0.5123, 0.2693, 0.9820, 0.8819]], dtype=torch.float64)